server:
  port: 8080

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tsdb}
    username: ${DB_USER:ts}
    password: ${DB_PASSWORD:ts}
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:8}
      minimum-idle: ${DB_MIN_IDLE:2}
      connection-timeout: 10000
      idle-timeout: ${DB_IDLE_TIMEOUT_MS:300000}
      max-lifetime: ${DB_MAX_LIFETIME_MS:1800000}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWKS_URI:http://localhost:8082/.well-known/jwks.json}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

security:
  auth:
    enabled: ${AUTH_ENABLED:false}
  admin:
    scope: ${ADMIN_SCOPE:admin:reindex}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

logging:
  file:
    name: logs/api-requests.log
  level:
    app.config.RequestLoggingFilter: INFO

search:
  opensearch:
    url: ${OPENSEARCH_URL:http://search:9200}



