name: Service CI

on:
  push:
    paths:
      - 'service/**'
      - '.github/workflows/ci-service-java.yml'
  pull_request:
    paths:
      - 'service/**'
      - '.github/workflows/ci-service-java.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: service
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build
